### ISSUE TITLE
Not generating thumb

### ISSUE THREAD

**Issue by flik** [angelitomg/QimageComponent#2]
I am trying but no results and no error in log...

$data['file'] = 'http://fc07.deviantart.net/fs71/f/2012/212/5/2/tumblr_background___loki___avengers_edition_by_miratheracusia-d57swys.gif';
		$data['width'] = '75';
		$data['output'] = WWW_ROOT.'/files/';
		
		echo 'img is : '.$this->Qimage->resize($data);

**Comment by angelitomg** [comment]
The source file must be on the local file system.

Good luck!

**Comment by flik** [comment]
Well. I have write some code for your component and It is working file for url. :)

You can add this function into your component for url

/**
		 * Method to getFileByUrl 
		 * 
		 * $data['file']        -> web url of image file
		 * */
		public function getFileByUrl($data=''){

			#$file = 'http://31.media.tumblr.com/fcb6f027cab033aaf594c76ecad62307/tumblr_myg30z1d2H1t4nrlno1_400.gif';			
			//debug($data);
			if(isset($data['file']))
				$isUrl = explode(':/',$data['file']);
			else
				return false;
			
			if(isset($isUrl[0]))
				$img = file_get_contents($data['file']);
				
			if(!empty($img)){
				$fileName = explode('/',strrev($data['file']));
				
				$newfile = WWW_ROOT.'/img/'.strrev($fileName[0]);
				 
				if(file_put_contents($newfile, $img)){
					chmod ($newfile , 0777 );
					$data['file'] = $newfile;
				}else
					return false;
						
				return $data;
			}		
		}

and then modify this code

if (!is_file($data['file'])){
				$data = $this->getFileByUrl($data);
				if (!is_file($data['file'])){
					$this->errors[] = 'Invalid file!';
					return false;
				}
			}

It is 100% working for url :)

**Comment by angelitomg** [comment]
You can create a fork and apply this patch.

Thank you for your contribution.

Cheers. ;)
